apiVersion: v1
kind: Service
metadata:
  name: free5gc-nrf-svc
spec:
  selector:
    app: free5gc-nrf
  clusterIP: None # 10.96.100.5
  ports:
    - name: sbi
      protocol: TCP
      port: 29510
---
apiVersion: apps/v1 
kind: Deployment
metadata:
  name: free5gc-nrf-deployment
spec:
  selector:
    matchLabels:
      app: free5gc-nrf
  replicas: 1
  template:
    metadata:
      labels:
        app: free5gc-nrf
    spec:
      containers:      
      - name: myapp-container
        image: free5gmano/free5gc-control-plane:stage3.0.4
        imagePullPolicy: IfNotPresent
        command: ["/bin/sh"]
        args: ["-c", "sleep 10s && ./bin/nrf"]
        volumeMounts:
        - name: nrfcfg
          mountPath: /go/src/free5gc/config/nrfcfg.conf
          subPath: nrfcfg.conf
        - name: free5gc
          mountPath: /go/src/free5gc/config/free5GC.conf
          subPath: free5GC.conf
      volumes:
      - name: nrfcfg
        configMap:
          name: free5gc-configmap
          items: 
          - key: nrfcfg.conf
            path: nrfcfg.conf
      - name: free5gc
        configMap:
          name: free5gc-configmap
          items: 
          - key: free5GC.conf
            path: free5GC.conf
      
