apiVersion: v1
kind: Service
metadata:
  name: free5gc-smf-svc
spec:
  selector:
    app: free5gc-smf
  clusterIP: None # 10.96.100.3
  ports:
    - name: sbi
      protocol: TCP
      port: 29502
    - name: pfcp
      protocol: UDP
      port: 8805
---
apiVersion: apps/v1 
kind: Deployment
metadata:
  name: free5gc-smf-deployment
spec:
  selector:
    matchLabels:
      app: free5gc-smf
  replicas: 1
  template:
    metadata:
      labels:
        app: free5gc-smf
    spec:
      containers:      
      - name: myapp-container
        image: free5gmano/free5gc-control-plane:stage3.0.4
        imagePullPolicy: IfNotPresent
        command: ["/bin/sh"]
        args: ["-c", "sleep 30s && ./bin/smf"]
        volumeMounts:
        - name: smfcfg
          mountPath: /go/src/free5gc/config/smfcfg.conf
          subPath: smfcfg.conf
        - name: uerouting
          mountPath: /go/src/free5gc/config/uerouting.yaml
          subPath: uerouting.yaml
        - name: free5gc
          mountPath: /go/src/free5gc/config/free5GC.conf
          subPath: free5GC.conf
      volumes:
      - name: smfcfg
        configMap:
          name: free5gc-configmap
          items: 
          - key: smfcfg.conf
            path: smfcfg.conf
      - name: uerouting
        configMap:
          name: free5gc-configmap
          items: 
          - key: uerouting.yaml
            path: uerouting.yaml
      - name: free5gc
        configMap:
          name: free5gc-configmap
          items: 
          - key: free5GC.conf
            path: free5GC.conf
      

