apiVersion: v1
kind: Service
metadata:
  name: free5gc-pcf-svc
spec:
  selector:
    app: free5gc-pcf
  ports:
    - name: sbi
      protocol: TCP
      port: 29507
---
apiVersion: apps/v1 
kind: Deployment
metadata:
  name: free5gc-pcf-deployment
spec:
  selector:
    matchLabels:
      app: free5gc-pcf
  replicas: 1
  template:
    metadata:
      labels:
        app: free5gc-pcf
    spec:
      containers:      
      - name: myapp-container
        image: free5gmano/free5gc-control-plane:stage3.0.4
        imagePullPolicy: IfNotPresent
        command: ["/bin/sh"]
        args: ["-c", "sleep 10s && ./bin/pcf"]
        volumeMounts:
        - name: pcfcfg
          mountPath: /go/src/free5gc/config/pcfcfg.conf
          subPath: pcfcfg.conf
        - name: free5gc
          mountPath: /go/src/free5gc/config/free5GC.conf
          subPath: free5GC.conf
      volumes:
      - name: pcfcfg
        configMap:
          name: free5gc-configmap
          items: 
          - key: pcfcfg.conf
            path: pcfcfg.conf
      - name: free5gc
        configMap:
          name: free5gc-configmap
          items: 
          - key: free5GC.conf
            path: free5GC.conf
      
