apiVersion: v1
kind: Service
metadata:
  name: free5gc-udm-svc
spec:
  selector:
    app: free5gc-udm
  ports:
    - name: sbi
      protocol: TCP
      port: 29503
---
apiVersion: apps/v1 
kind: Deployment
metadata:
  name: free5gc-udm-deployment
spec:
  selector:
    matchLabels:
      app: free5gc-udm
  replicas: 1
  template:
    metadata:
      labels:
        app: free5gc-udm
    spec:
      containers:      
      - name: myapp-container
        image: free5gmano/free5gc-control-plane:stage3.0.4
        imagePullPolicy: Never
        command: ["/bin/sh"]
        args: ["-c", "sleep 10s && ./bin/udm"]
        volumeMounts:
        - name: udmcfg
          mountPath: /go/src/free5gc/config/udmcfg.conf
          subPath: udmcfg.conf
        - name: free5gc
          mountPath: /go/src/free5gc/config/free5GC.conf
          subPath: free5GC.conf
      volumes:
      - name: udmcfg
        configMap:
          name: free5gc-configmap
          items: 
          - key: udmcfg.conf
            path: udmcfg.conf
      - name: free5gc
        configMap:
          name: free5gc-configmap
          items: 
          - key: free5GC.conf
            path: free5GC.conf
      
