apiVersion: v1
kind: Service
metadata:
  name: free5gc-nssf-svc
spec:
  selector:
    app: free5gc-nssf
  ports:
    - name: sbi
      protocol: TCP
      port: 29531
---
apiVersion: apps/v1 
kind: Deployment
metadata:
  name: free5gc-nssf-deployment
spec:
  selector:
    matchLabels:
      app: free5gc-nssf
  replicas: 1
  template:
    metadata:
      labels:
        app: free5gc-nssf
    spec:
      containers:      
      - name: myapp-container
        image: free5gmano/free5gc-control-plane:stage3.0.4
        imagePullPolicy: Never
        command: ["/bin/sh"]
        args: ["-c", "sleep 10s && ./bin/nssf"]
        volumeMounts:
        - name: nssfcfg
          mountPath: /go/src/free5gc/config/nssfcfg.conf
          subPath: nssfcfg.conf
        - name: free5gc
          mountPath: /go/src/free5gc/config/free5GC.conf
          subPath: free5GC.conf
      volumes:
      - name: nssfcfg
        configMap:
          name: free5gc-configmap
          items: 
          - key: nssfcfg.conf
            path: nssfcfg.conf
      - name: free5gc
        configMap:
          name: free5gc-configmap
          items: 
          - key: free5GC.conf
            path: free5GC.conf
      
