apiVersion: v1
kind: Service
metadata:
  name: free5gc-amf-svc
spec:
  selector:
    app: free5gc-amf
  ports:
    - name: sbi
      protocol: TCP
      port: 29518
    - name: sctp
      protocol: SCTP
      port: 38412
