apiVersion: v1
kind: Service
metadata:
  name: free5gc-smf-svc
spec:
  selector:
    app: free5gc-smf
  clusterIP: None # 10.96.100.3
  ports:
    - name: sbi
      protocol: TCP
      port: 29502
    - name: pfcp
      protocol: UDP
      port: 8805      

