apiVersion: v1
kind: ConfigMap
metadata:
  name: free5gc-amf-configmap
data:
  amfcfg.yaml: |
    info:
      version: 1.0.3
      description: AMF initial local configuration

    configuration:
      amfName: AMF # the name of this AMF
      ngapIpList:  # the IP list of N2 interfaces on this AMF
        - free5gc-amf-svc
      sbi: # Service-based interface information
        scheme: http # the protocol for sbi (http or https)
        registerIPv4: free5gc-amf-svc # IP used to register to NRF
        bindingIPv4: free5gc-amf-svc  # IP used to bind the service
        port: 8000 # port used to bind the service
        tls: # the local path of TLS key
          pem: config/TLS/amf.pem # AMF TLS Certificate
          key: config/TLS/amf.key # AMF TLS Private key
      serviceNameList: # the SBI services provided by this AMF, refer to TS 29.518
        - namf-comm # Namf_Communication service
        - namf-evts # Namf_EventExposure service
        - namf-mt   # Namf_MT service
        - namf-loc  # Namf_Location service
        - namf-oam  # OAM service
      servedGuamiList: # Guami (Globally Unique AMF ID) list supported by this AMF
        # <GUAMI> = <MCC><MNC><AMF ID>
        - plmnId: # Public Land Mobile Network ID, <PLMN ID> = <MCC><MNC>
            mcc: 208 # Mobile Country Code (3 digits string, digit: 0~9)
            mnc: 93 # Mobile Network Code (2 or 3 digits string, digit: 0~9)
          amfId: cafe00 # AMF identifier (3 bytes hex string, range: 000000~FFFFFF)
      supportTaiList:  # the TAI (Tracking Area Identifier) list supported by this AMF
        - plmnId: # Public Land Mobile Network ID, <PLMN ID> = <MCC><MNC>
            mcc: 208 # Mobile Country Code (3 digits string, digit: 0~9)
            mnc: 93 # Mobile Network Code (2 or 3 digits string, digit: 0~9)
          tac: 1 # Tracking Area Code (uinteger, range: 0~16777215)
      plmnSupportList: # the PLMNs (Public land mobile network) list supported by this AMF
        - plmnId: # Public Land Mobile Network ID, <PLMN ID> = <MCC><MNC>
            mcc: 208 # Mobile Country Code (3 digits string, digit: 0~9)
            mnc: 93 # Mobile Network Code (2 or 3 digits string, digit: 0~9)
          snssaiList: # the S-NSSAI (Single Network Slice Selection Assistance Information) list supported by this AMF
            - sst: 1 # Slice/Service Type (uinteger, range: 0~255)
              sd: 010203 # Slice Differentiator (3 bytes hex string, range: 000000~FFFFFF)
            - sst: 1 # Slice/Service Type (uinteger, range: 0~255)
              sd: 112233 # Slice Differentiator (3 bytes hex string, range: 000000~FFFFFF)
      supportDnnList:  # the DNN (Data Network Name) list supported by this AMF
        - internet
      nrfUri: http://free5gc-nrf-svc:8000 # a valid URI of NRF
      security:  # NAS security parameters
        integrityOrder: # the priority of integrity algorithms
          - NIA2
          # - NIA0
        cipheringOrder: # the priority of ciphering algorithms
          - NEA0
          # - NEA2
      networkName:  # the name of this core network
        full: free5GC
        short: free
      locality: area1 # Name of the location where a set of AMF, SMF and UPFs are located
      networkFeatureSupport5GS: # 5gs Network Feature Support IE, refer to TS 24.501
        enable: true # append this IE in Registration accept or not
        length: 1 # IE content length (uinteger, range: 1~3)
        imsVoPS: 0 # IMS voice over PS session indicator (uinteger, range: 0~1)
        emc: 0 # Emergency service support indicator for 3GPP access (uinteger, range: 0~3)
        emf: 0 # Emergency service fallback indicator for 3GPP access (uinteger, range: 0~3)
        iwkN26: 0 # Interworking without N26 interface indicator (uinteger, range: 0~1)
        mpsi: 0 # MPS indicator (uinteger, range: 0~1)
        emcN3: 0 # Emergency service support indicator for Non-3GPP access (uinteger, range: 0~1)
        mcsi: 0 # MCS indicator (uinteger, range: 0~1)
      t3502Value: 720  # timer value (seconds) at UE side
      t3512Value: 3600 # timer value (seconds) at UE side
      non3gppDeregistrationTimerValue: 3240 # timer value (seconds) at UE side
      # retransmission timer for paging message
      t3513:
        enable: true     # true or false
        expireTime: 6s   # default is 6 seconds
        maxRetryTimes: 4 # the max number of retransmission
      # retransmission timer for NAS Deregistration Request message
      t3522:
        enable: true     # true or false
        expireTime: 6s   # default is 6 seconds
        maxRetryTimes: 4 # the max number of retransmission
      # retransmission timer for NAS Registration Accept message
      t3550:
        enable: true     # true or false
        expireTime: 6s   # default is 6 seconds
        maxRetryTimes: 4 # the max number of retransmission
      # retransmission timer for NAS Authentication Request/Security Mode Command message
      t3560:
        enable: true     # true or false
        expireTime: 6s   # default is 6 seconds
        maxRetryTimes: 4 # the max number of retransmission
      # retransmission timer for NAS Notification message
      t3565:
        enable: true     # true or false
        expireTime: 6s   # default is 6 seconds
        maxRetryTimes: 4 # the max number of retransmission
      t3570:
        enable: true     # true or false
        expireTime: 6s   # default is 6 seconds
        maxRetryTimes: 4 # the max number of retransmission
    # the kind of log output
      # debugLevel: how detailed to output, value: trace, debug, info, warn, error, fatal, panic
      # ReportCaller: enable the caller report or not, value: true or false
    logger:
      AMF:
        debugLevel: info
        ReportCaller: false
      NAS:
        debugLevel: info
        ReportCaller: false
      FSM:
        debugLevel: info
        ReportCaller: false
      NGAP:
        debugLevel: info
        ReportCaller: false
      Aper:
        debugLevel: info
        ReportCaller: false
      PathUtil:
        debugLevel: info
        ReportCaller: false
      OpenApi:
        debugLevel: info
        ReportCaller: false

---
apiVersion: v1
kind: Service
metadata:
  name: free5gc-amf-svc
spec:
  selector:
    app: free5gc-amf
  clusterIP: None # 10.96.100.2
  ports:
    - name: sctp
      protocol: SCTP
      port: 38412
    - name: sbi
      protocol: TCP
      port: 29518
--- 
apiVersion: apps/v1 
kind: Deployment
metadata:
  name: free5gc-amf-deployment
spec:
  selector:
    matchLabels:
      app: free5gc-amf
  replicas: 1
  template:
    metadata:
      labels:
        app: free5gc-amf
    spec:
      containers:      
      - name: myapp-container
        image: free5gmano/free5gc-control-plane:stage3.2.1-amd64
        command: ["/bin/sh"]
        args: ["-c", "sleep 5s && ./bin/amf"]
        env:
        - name: GIN_MODE
          value: debug # debug | release
        volumeMounts:
        - name: amfcfg
          mountPath: /free5gc/config/amfcfg.yaml
          subPath: amfcfg.yaml
      volumes:
      - name: amfcfg
        configMap:
          name: free5gc-amf-configmap
          items: 
          - key: amfcfg.yaml
            path: amfcfg.yaml
