apiVersion: v1
kind: ConfigMap
metadata:
  name: free5gc-udm-configmap
data:
  udmcfg.yaml: |
    info:
      version: 1.0.2
      description: UDM initial local configuration

    configuration:
      serviceNameList: # the SBI services provided by this UDM, refer to TS 29.503
        - nudm-sdm # Nudm_SubscriberDataManagement service
        - nudm-uecm # Nudm_UEContextManagement service
        - nudm-ueau # Nudm_UEAuthenticationManagement service
        - nudm-ee # Nudm_EventExposureManagement service
        - nudm-pp # Nudm_ParameterProvisionDataManagement service
      sbi: # Service-based interface information
        scheme: http # the protocol for sbi (http or https)
        registerIPv4: free5gc-udm-svc # IP used to register to NRF
        bindingIPv4: free5gc-udm-svc  # IP used to bind the service
        port: 8000 # Port used to bind the service
        tls: # the local path of TLS key
          log: config/TLS/udmsslkey.log # UDM keylog
          pem: config/TLS/udm.pem # UDM TLS Certificate
          key: config/TLS/udm.key # UDM TLS Private key
      nrfUri: http://free5gc-nrf-svc:8000 # a valid URI of NRF

      # test data set from TS33501-f60 Annex C.4
      SuciProfile:
        - ProtectionScheme: 1 # Protect Scheme: Profile A
          PrivateKey: c53c22208b61860b06c62e5406a7b330c2b577aa5558981510d128247d38bd1d
          PublicKey: 5a8d38864820197c3394b92613b20b91633cbd897119273bf8e4a6f4eec0a650
        - ProtectionScheme: 2 # Protect Scheme: Profile B
          PrivateKey: F1AB1074477EBCC7F554EA1C5FC368B1616730155E0041AC447D6301975FECDA
          PublicKey: 0472DA71976234CE833A6907425867B82E074D44EF907DFB4B3E21C1C2256EBCD15A7DED52FCBB097A4ED250E036C7B9C8C7004C4EEDC4F068CD7BF8D3F900E3B4

    # the kind of log output
      # debugLevel: how detailed to output, value: trace, debug, info, warn, error, fatal, panic
      # ReportCaller: enable the caller report or not, value: true or false
    logger:
      UDM:
        debugLevel: info
        ReportCaller: false
      OpenApi:
        debugLevel: info
        ReportCaller: false
      PathUtil:
        debugLevel: info
        ReportCaller: false
---
apiVersion: v1
kind: Service
metadata:
  name: free5gc-udm-svc
spec:
  selector:
    app: free5gc-udm
  clusterIP: None # 10.96.100.7
  ports:
    - name: sbi
      protocol: TCP
      port: 29503
---
apiVersion: apps/v1 
kind: Deployment
metadata:
  name: free5gc-udm-deployment
spec:
  selector:
    matchLabels:
      app: free5gc-udm
  replicas: 1
  template:
    metadata:
      labels:
        app: free5gc-udm
    spec:
      containers:      
      - name: myapp-container
        image: free5gmano/free5gc-control-plane:stage3.2.1-amd64
        command: ["/bin/sh"]
        args: ["-c", "sleep 5s && ./bin/udm"]
        volumeMounts:
        - name: udmcfg
          mountPath: /free5gc/config/udmcfg.yaml
          subPath: udmcfg.yaml
      volumes:
      - name: udmcfg
        configMap:
          name: free5gc-udm-configmap
          items: 
          - key: udmcfg.yaml
            path: udmcfg.yaml
      
