apiVersion: v1
kind: Service
metadata:
  name: mongodb-svc
spec:
  ports:
  - port: 27017
  selector:
    app: free5gc-mongodb
  clusterIP: None
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: free5gc-mongodb
spec:
  selector:
    matchLabels:
      app: free5gc-mongodb
  template:
    metadata:
      labels:
        app: free5gc-mongodb
    spec:
      containers:
      - image: free5gmano/nextepc-mongodb
        name: free5gc-mongodb
        ports:
        - containerPort: 27017
          name: mongodb
