apiVersion: v1
kind: ConfigMap
metadata:
  name: ueransim-ue-configmap
data:
  free5gc-ue.yaml: |
    # IMSI number of the UE. IMSI = [MCC|MNC|MSISDN] (In total 15 digits)
    supi: 'imsi-208930000000003'
    # Mobile Country Code value of HPLMN
    mcc: '208'
    # Mobile Network Code value of HPLMN (2 or 3 digits)
    mnc: '93'

    # Permanent subscription key
    key: '8baf473f2f8fd09487cccbd7097c6862'
    # Operator code (OP or OPC) of the UE
    op: '8e27b6af0e692e750f32667a3b14605d'
    # This value specifies the OP type and it can be either 'OP' or 'OPC'
    opType: 'OP'
    # Authentication Management Field (AMF) value
    amf: '8000'
    # IMEI number of the device. It is used if no SUPI is provided
    imei: '356938035643803'
    # IMEISV number of the device. It is used if no SUPI and IMEI is provided
    imeiSv: '4370816125816151'

    # List of gNB IP addresses for Radio Link Simulation
    gnbSearchList:
      - 192.168.223.24

    # UAC Access Identities Configuration
    uacAic:
      mps: false
      mcs: false

    # UAC Access Control Class
    uacAcc:
      normalClass: 0
      class11: false
      class12: false
      class13: false
      class14: false
      class15: false

    # Initial PDU sessions to be established
    sessions:
      - type: 'IPv4'
        apn: 'internet'
        slice:
          sst: 0x01
          sd: 0x010203

    # Configured NSSAI for this UE by HPLMN
    configured-nssai:
      - sst: 0x01
        sd: 0x010203

    # Default Configured NSSAI for this UE
    default-nssai:
      - sst: 1
        sd: 1

    # Supported integrity algorithms by this UE
    integrity:
      IA1: true
      IA2: true
      IA3: true

    # Supported encryption algorithms by this UE
    ciphering:
      EA1: true
      EA2: true
      EA3: true

    # Integrity protection maximum data rate for user plane
    integrityMaxRate:
      uplink: 'full'
      downlink: 'full'
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ueransim-ue-deployment
  labels:
    app: ueransim-ue
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ueransim-ue
  template:
    metadata:
      labels:
        app: ueransim-ue
    spec:
      containers:
      - name: ueransim-ue
        image: free5gmano/ueransim:v3.2.5
        securityContext:
          privileged: true
        command: ["/bin/bash", "-c"]
        args: ["./build/nr-ue -c ./config/free5gc-ue.yaml"]
        volumeMounts:
        - mountPath: /dev/net/tun
          name: tun-volume
        - name: ue-conf
          mountPath: /UERANSIM/config/free5gc-ue.yaml
          subPath: free5gc-ue.yaml
      volumes:
      - name: tun-volume
        hostPath:
          path: /dev/net/tun
      - name: ue-conf
        configMap:
          name: ueransim-ue-configmap
          items: 
          - key: free5gc-ue.yaml
            path: free5gc-ue.yaml
