apiVersion: v1
kind: ConfigMap
metadata:
  name: free5gc-udm-configmap
data:
  udmcfg.yaml: |
    info:
      version: 1.0.1
      description: UDM initial local configuration

    configuration:
      serviceNameList: # the SBI services provided by this UDM, refer to TS 29.503
        - nudm-sdm # Nudm_SubscriberDataManagement service
        - nudm-uecm # Nudm_UEContextManagement service
        - nudm-ueau # Nudm_UEAuthenticationManagement service
        - nudm-ee # Nudm_EventExposureManagement service
        - nudm-pp # Nudm_ParameterProvisionDataManagement service
      sbi: # Service-based interface information
        scheme: http # the protocol for sbi (http or https)
        registerIPv4: 192.168.2.167 # IP used to register to NRF
        bindingIPv4: 192.168.2.167  # IP used to bind the service
        port: 8000 # Port used to bind the service
        tls: # the local path of TLS key
          log: free5gc/udmsslkey.log # UDM keylog
          pem: free5gc/support/TLS/udm.pem # UDM TLS Certificate
          key: free5gc/support/TLS/udm.key # UDM TLS Private key
      nrfUri: http://192.168.2.165:8000 # a valid URI of NRF

      # test data set from TS33501-f60 Annex C.4
      SuciProfile:
        - ProtectionScheme: 1 # Protect Scheme: Profile A
          PrivateKey: c53c22208b61860b06c62e5406a7b330c2b577aa5558981510d128247d38bd1d
          PublicKey: 5a8d38864820197c3394b92613b20b91633cbd897119273bf8e4a6f4eec0a650
        - ProtectionScheme: 2 # Protect Scheme: Profile B
          PrivateKey: F1AB1074477EBCC7F554EA1C5FC368B1616730155E0041AC447D6301975FECDA
          PublicKey: 0472DA71976234CE833A6907425867B82E074D44EF907DFB4B3E21C1C2256EBCD15A7DED52FCBB097A4ED250E036C7B9C8C7004C4EEDC4F068CD7BF8D3F900E3B4

    # the kind of log output
      # debugLevel: how detailed to output, value: trace, debug, info, warn, error, fatal, panic
      # ReportCaller: enable the caller report or not, value: true or false
    logger:
      UDM:
        debugLevel: info
        ReportCaller: false
      OpenApi:
        debugLevel: info
        ReportCaller: false
      PathUtil:
        debugLevel: info
        ReportCaller: false

---
apiVersion: apps/v1 
kind: Deployment
metadata:
  name: free5gc-udm-deployment
spec:
  selector:
    matchLabels:
      app: free5gc-udm
  replicas: 1
  template:
    metadata:
      labels:
        app: free5gc-udm
    spec:
      containers:      
      - name: myapp-container
        image: free5gmano/free5gc-control-plane:stage3.0.6-amd64
        command: ["/bin/sh"]
        args: ["-c", "./bin/udm"]
        volumeMounts:
        - name: udmcfg
          mountPath: /free5gc/config/udmcfg.yaml
          subPath: udmcfg.yaml
      initContainers:
      - name: init-network-client
        image: sdnvortex/network-controller:v0.4.9
        command: ["/go/bin/client"]
        args: ["-s=unix:///tmp/vortex.sock", "-b=br1", "-n=eth1", "-i=192.168.2.167/23"]
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: POD_UUID
          valueFrom:
            fieldRef:
              fieldPath: metadata.uid
        volumeMounts:
        - mountPath: /tmp/
          name: grpc-sock
      volumes:
      - name: grpc-sock
        hostPath:
          path: /tmp/vortex/
      - name: udmcfg
        configMap:
          name: free5gc-udm-configmap
          items: 
          - key: udmcfg.yaml
            path: udmcfg.yaml
      
