apiVersion: v1
kind: ConfigMap
metadata:
  name: free5gc-ausf-configmap
data:
  ausfcfg.yaml: |
    info:
      version: 1.0.0
      description: AUSF initial local configuration

    configuration:
      sbi:                                    # Service-based interface information
        scheme: http                          # the protocol for sbi (http or https)
        registerIPv4: 192.168.2.164           # IP used to register to NRF
        bindingIPv4: 192.168.2.164            # IP used to bind the service
        port: 8000                            # Port used to bind the service
      serviceNameList:                        # the SBI services provided by this AUSF, refer to TS 29.509
        - nausf-auth                          # Nausf_UEAuthentication service
      nrfUri: http://192.168.2.165:8000       # a valid URI of NRF
      plmnSupportList:                        # the PLMNs (Public Land Mobile Network) list supported by this AUSF
        - mcc: 208                            # Mobile Country Code (3 digits string, digit: 0~9)
          mnc: 93                             # Mobile Network Code (2 or 3 digits string, digit: 0~9)
        - mcc: 123
          mnc: 45
      groupId: ausfGroup001                   # ID for the group of the AUSF

    # the kind of log output
    # debugLevel: how detailed to output, value: trace, debug, info, warn, error, fatal, panic
    # ReportCaller: enable the caller report or not, value: true or false
    logger:
      AUSF:
        debugLevel: info
        ReportCaller: false
      PathUtil:
        debugLevel: info
        ReportCaller: false
      OpenApi:
        debugLevel: info
        ReportCaller: false
---
apiVersion: apps/v1 
kind: Deployment
metadata:
  name: free5gc-ausf-deployment
spec:
  selector:
    matchLabels:
      app: free5gc-ausf
  replicas: 1
  template:
    metadata:
      labels:
        app: free5gc-ausf
    spec:
      containers:      
      - name: myapp-container
        image: free5gmano/free5gc-control-plane:stage3.0.6-amd64
        command: ["/bin/sh"]
        args: ["-c", "./bin/ausf"]
        env:
        - name: GIN_MODE
          value: debug # debug | release
        volumeMounts:
        - name: ausfcfg
          mountPath: /free5gc/config/ausfcfg.yaml
          subPath: ausfcfg.yaml
      initContainers:
      - name: init-network-client
        image: sdnvortex/network-controller:v0.4.9
        command: ["/go/bin/client"]
        args: ["-s=unix:///tmp/vortex.sock", "-b=br1", "-n=eth1", "-i=192.168.2.164/23"]
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: POD_UUID
          valueFrom:
            fieldRef:
              fieldPath: metadata.uid
        volumeMounts:
        - mountPath: /tmp/
          name: grpc-sock
      volumes:
      - name: grpc-sock
        hostPath:
          path: /tmp/vortex/
      - name: ausfcfg
        configMap:
          name: free5gc-ausf-configmap
          items: 
          - key: ausfcfg.yaml
            path: ausfcfg.yaml