apiVersion: v1
kind: ConfigMap
metadata:
  name: free5gc-amf-configmap
data:
  amfcfg.yaml: |
    info:
      version: 1.0.2
      description: AMF initial local configuration

    configuration:
      amfName: AMF                            # the name of this AMF
      ngapIpList:                             # the IP list of N2 interfaces on this AMF
        - 0.0.0.0
      sbi:                                    # Service-based interface information
        scheme: http                          # the protocol for sbi (http or https)
        registerIPv4: free5gc-amf-svc         # IP used to register to NRF
        bindingIPv4: 0.0.0.0                  # IP used to bind the service
        port: 29518                           # port used to bind the service
      serviceNameList:                        # the SBI services provided by this AMF, refer to TS 29.518
        - namf-comm                           # Namf_Communication service
        - namf-evts                           # Namf_EventExposure service
        - namf-mt                             # Namf_MT service
        - namf-loc                            # Namf_Location service
        - namf-oam                            # OAM service
      servedGuamiList:                        # Guami (Globally Unique AMF ID) list supported by this AMF
      # <GUAMI> = <MCC><MNC><AMF ID>
        - plmnId:                             # Public Land Mobile Network ID, <PLMN ID> = <MCC><MNC>
            mcc: 208                          # Mobile Country Code (3 digits string, digit: 0~9)
            mnc: 93                           # Mobile Network Code (2 or 3 digits string, digit: 0~9)
          amfId: cafe00                       # AMF identifier (3 bytes hex string, range: 000000~FFFFFF)
      supportTaiList:                         # the TAI (Tracking Area Identifier) list supported by this AMF
        - plmnId:
            mcc: 208
            mnc: 93
          tac: 1                              # Tracking Area Code (uinteger, range: 0~16777215)
      plmnSupportList:                        # the PLMNs (Public land mobile network) list supported by this AMF
        - plmnId:
            mcc: 208
            mnc: 93
          snssaiList:                         # the S-NSSAI (Single Network Slice Selection Assistance Information) list supported by this AMF
            - sst: 1
              sd: 010203
            - sst: 1
              sd: 112233
      supportDnnList:                         # the DNN (Data Network Name) list supported by this AMF
        - internet
      nrfUri: http://free5gc-nrf-svc.5gc:29510    # a valid URI of NRF
      security:                               # NAS security parameters
        integrityOrder:                       # the priority of integrity algorithms
          - NIA2
          - NIA0
        cipheringOrder:                       # the priority of ciphering algorithms
          - NEA0
          - NEA2
      networkName:                            # the name of this core network
        full: free5GC
        short: free
      t3502Value: 720                         # timer value (seconds) at UE side
      t3512Value: 3600                        # timer value (seconds) at UE side
      non3gppDeregistrationTimerValue: 3240   # timer value (seconds) at UE side
      # retransmission timer for paging message
      t3513:
        enable: true                          # true or false
        expireTime: 6s                        # default is 6 seconds
        maxRetryTimes: 4                      # the max number of retransmission
      # retransmission timer for NAS Deregistration Request message
      t3522:
        enable: true
        expireTime: 6s
        maxRetryTimes: 4
      # retransmission timer for NAS Registration Accept message
      t3550:
        enable: true
        expireTime: 6s
        maxRetryTimes: 4
      # retransmission timer for NAS Authentication Request/Security Mode Command message
      t3560:
        enable: true
        expireTime: 6s
        maxRetryTimes: 4
      # retransmission timer for NAS Notification message
      t3565:
        enable: true
        expireTime: 6s
        maxRetryTimes: 4

    # the kind of log output
    # debugLevel: how detailed to output, value: trace, debug, info, warn, error, fatal, panic
    # ReportCaller: enable the caller report or not, value: true or false
    logger:
      AMF:
        debugLevel: debug
        ReportCaller: true
      NAS:
        debugLevel: debug
        ReportCaller: true
      FSM:
        debugLevel: debug
        ReportCaller: true
      NGAP:
        debugLevel: debug
        ReportCaller: true
      Aper:
        debugLevel: debug
        ReportCaller: true
      PathUtil:
        debugLevel: debug
        ReportCaller: true
      OpenApi:
        debugLevel: debug
        ReportCaller: true
---
apiVersion: v1
kind: Service
metadata:
  name: free5gc-amf-svc
spec:
  selector:
    app: free5gc-amf
  ports:
    - name: sbi
      protocol: TCP
      port: 29518
    - name: sctp
      protocol: SCTP
      port: 38412
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: free5gc-amf-deployment
spec:
  selector:
    matchLabels:
      app: free5gc-amf
  replicas: 1
  template:
    metadata:
      labels:
        app: free5gc-amf
    spec:
      containers:
      - name: myapp-container
        image: free5gmano/free5gc-control-plane:stage3.0.6-amd64
        command: ["/bin/sh"]
        args: ["-c", "sleep 5s && ./bin/amf"]
        env:
        - name: GIN_MODE
          value: debug # debug | release
        volumeMounts:
        - name: amfcfg
          mountPath: /free5gc/config/amfcfg.yaml
          subPath: amfcfg.yaml
      volumes:
      - name: amfcfg
        configMap:
          name: free5gc-amf-configmap
          items: 
          - key: amfcfg.yaml
            path: amfcfg.yaml