apiVersion: v1
kind: ConfigMap
metadata:
  name: ueransim-ue3-configmap
data:
  free5gc-ue.yaml: |
    # IMSI number of the UE. IMSI = [MCC|MNC|MSISDN] (In total 15 or 16 digits)
    supi: 'imsi-208930000000005'
    # Mobile Country Code value
    mcc: '208'
    # Mobile Network Code value (2 or 3 digits)
    mnc: '93'
    # Permanent subscription key
    key: '8baf473f2f8fd09487cccbd7097c6862'
    # Operator code (OP or OPC) of the UE
    op: '8e27b6af0e692e750f32667a3b14605d'
    # This value specifies the OP type and it can be either 'OP' or 'OPC'
    opType: 'OP'
    # Authentication Management Field (AMF) value
    amf: '8000'
    # IMEI number of the device. It is used if no SUPI is provided
    imei: '356938035643803'
    # IMEISV number of the device. It is used if no SUPI and IMEI is provided
    imeiSv: '4370816125816151'
    # List of gNB IP addresses for Radio Link Simulation
    gnbSearchList:
      - 10.244.0.249
    # Initial PDU sessions to be established
    sessions:
      - type: 'IPv4'
        apn: 'internet'
        slice:
          sst: 0x01
          sd: 0x010203
    # Before v3.1.1 version
    # # List of requested S-NSSAIs by this UE
    # slices:
    #   - sst: 0x01
    #     sd: 0x010203

    # After v3.1.1 version
    # Configured NSSAI for this UE by HPLMN
    configured-nssai:
      - sst: 0x01
        sd: 0x010203

    # Default Configured NSSAI for this UE
    default-nssai:
      - sst: 1
        sd: 1

    # Supported encryption and integrity algorithms by this UE
    integrity:
      IA1: true
      IA2: true
      IA3: true
    ciphering:
      EA1: true
      EA2: true
      EA3: true
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ueransim-ue3-deployment
  labels:
    app: ueransim-ue3
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ueransim-ue3
  template:
    metadata:
      labels:
        app: ueransim-ue3
    spec:
      containers:
      - name: ueransim-ue3
        image: j13tw/ueransim:latest
        securityContext:
          privileged: true
        command: ["/bin/bash", "-c"]
        args: ["./build/nr-ue -c ./config/free5gc-ue.yaml"]
        volumeMounts:
        - mountPath: /dev/net/tun
          name: tun-volume
        - name: ue-conf
          mountPath: /UERANSIM/config/free5gc-ue.yaml
          subPath: free5gc-ue.yaml
      volumes:
      - name: tun-volume
        hostPath:
          path: /dev/net/tun
      - name: ue-conf
        configMap:
          name: ueransim-ue3-configmap
          items:
          - key: free5gc-ue.yaml
            path: free5gc-ue.yaml
